### ISSUE TITLE
Update to new share API

### ISSUE THREAD

**Issue by MorrisJobke** [vnc-biz/appvncsafe#2]
Hi developers of the appvncsafe app,

while looking at our code we found out that you are using some APIs, that we want to get rid of, because they are the old way of how to retrieve shares and are likely to malfunction even as of now.

`OCP\Share::getItemSharedWithBySource()`:

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L397

`OCP\Share::getItemsShared()`:

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L355

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L407

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L429

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L470

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L495

`OCP\Share::getItemShared()`:

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L419

https://github.com/vnc-biz/appvncsafe/blob/3b95f1ab1b23e2cc5ea43a9bd4d4924601fda7e5/appvncsafe/controller/servicecontroller.php#L482

Maybe @rullzer can provide more information on how to fix this.

**Comment by kapilnadiyapara** [comment]
@MorrisJobke and @rullzer I have checked the latest code  of owncloud core. I found that the Share class https://github.com/owncloud/core/blob/master/lib/private/Share/Share.php which we have used that is not deprecated and it`s function also.

Could you please provide me link of new share api ?

Thanks You.

**Comment by rullzer** [comment]
You should use the sharemanager: https://github.com/nextcloud/server/blob/master/lib/public/Share/IManager.php

Let me check if I can provide you with a quick PR to get started

**Comment by rullzer** [comment]
Ah this should have gone into https://github.com/vnc-biz/nextcloud-appvncsafe :)

**Comment by MorrisJobke** [comment]
Okay - this seems to be the wrong repo, as this app only installs on ownCloud due to the limitations of the `info.xml` - let's focus on the Nextcloud part: https://github.com/vnc-biz/nextcloud-appvncsafe/issues/2

Sorry for the noise.
